/*L
  Copyright Washington University at St. Louis

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/geneconnect/LICENSE.txt for details.
L*/

CREATE TABLESPACE "GENECONNECTDATA" LOGGING 
DATAFILE '$ORACLE_HOME/GENECONNECTDATA01.ora' SIZE 16384M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO MAXSIZE UNLIMITED ;

CREATE USER GENECONNECTUSER PROFILE DEFAULT IDENTIFIED BY GENECONNECTUSER DEFAULT TABLESPACE GENECONNECTDATA TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
 
GRANT CREATE ANY INDEX TO GENECONNECTUSER;
GRANT CREATE ANY TABLE TO GENECONNECTUSER;
GRANT CREATE PUBLIC SYNONYM TO GENECONNECTUSER;
GRANT UNLIMITED TABLESPACE TO GENECONNECTUSER;
GRANT CONNECT TO GENECONNECTUSER;
GRANT SELECT ANY TABLE TO GENECONNECTUSER;
GRANT CREATE  SESSION TO GENECONNECTUSER;
