ALTER INDEX DATASOURCE_INDEX REBUILD  NOPARALLEL  NOLOGGING 
;

ALTER INDEX LINKTYPE_INDEX REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX DATASOURCE_LINKS_INDEX REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX PATH_INDEX_ID REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX PATH_INDEX_DATASOURCE_IDS REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX SUBPATH_INDEX_ID REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX SUBPATH_INDEX_PATHIDS REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX BASETABLE_INDEX_ID REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX BASETABLE_INDEX_DATASOURCE_IDS REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX COLUMN_METADATA_INDEX REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX TABLEJOIN_METADATA_INDEX REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX ONT_INDEX REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX PATH_ONT_INDEX_PATHID REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX PATH_ONT_INDEX_ONTID REBUILD NOPARALLEL NOLOGGING 
;

ALTER INDEX GENOMIC_IDENTIFIER_INDEX  REBUILD NOPARALLEL NOLOGGING 
;