INSERT INTO BASETABLE_METADATA VALUES(0,'ENSEMBLGENE_ENTREZGENE',0,1);
INSERT INTO BASETABLE_METADATA VALUES(1,'ENSEMBLGENE_UNIGENE',0,2);
INSERT INTO BASETABLE_METADATA VALUES(2,'ENSEMBLGENE_ENSEMBLTRANS',0,4);

INSERT INTO BASETABLE_METADATA VALUES(3,'ENTREZGENE_ENSEMBLGENE',1,0);
INSERT INTO BASETABLE_METADATA VALUES(4,'ENTREZ_UNIGENE',1,2);
INSERT INTO BASETABLE_METADATA VALUES(5,'ENTREZGENE_REFSEQMRNA',1,5);

INSERT INTO BASETABLE_METADATA VALUES(6,'UNIGENE_ENSEMBLGENE',2,0);
INSERT INTO BASETABLE_METADATA VALUES(7,'UNIGENE_ENTREZ',2,1);

INSERT INTO BASETABLE_METADATA VALUES(8,'GENBANKMRNA_ENSEMBLTRANS',3,4);
INSERT INTO BASETABLE_METADATA VALUES(9,'GENBANKMRNA_REFSEQMRNA',3,5);

INSERT INTO BASETABLE_METADATA VALUES(10,'ENSEMBLTRANS_REFSEQMRNA',4,5);
INSERT INTO BASETABLE_METADATA VALUES(11,'ENSEMBLTRANS_ENSEMBLPROT',4,6);

INSERT INTO BASETABLE_METADATA VALUES(12,'REFSEQMRNA_ENSEMBLTRANS',5,4);
INSERT INTO BASETABLE_METADATA VALUES(13,'REFSEQMRNA_REFSEQPROTEIN',5,7);

INSERT INTO BASETABLE_METADATA VALUES(14,'ENSEMBLPROT_REFSEQPROTEIN',6,7);
INSERT INTO BASETABLE_METADATA VALUES(15,'ENSEMBLPROT_UNIPROT',6,9);

INSERT INTO BASETABLE_METADATA VALUES(16,'REFSEQPROTEIN_ENSEMBLPROT',7,6);
INSERT INTO BASETABLE_METADATA VALUES(17,'REFSEQPROTEIN_UNIPROT',7,9);

INSERT INTO BASETABLE_METADATA VALUES(18,'GENBANKPROT_ENSEMBLPROT',8,6);
INSERT INTO BASETABLE_METADATA VALUES(19,'GENBANKPROT_REFSEQPROTEIN',8,7);
INSERT INTO BASETABLE_METADATA VALUES(20,'GENBANKPROT_UNIPROT',8,9);

INSERT INTO BASETABLE_METADATA VALUES(21,'UNIPROT_ENSEMBLPROT',9,6);
INSERT INTO BASETABLE_METADATA VALUES(22,'UNIPROT_REFSEQPROTEIN',9,7);
INSERT INTO BASETABLE_METADATA VALUES(23,'UNIPROT_GENBANKPROTEIN',9,8);

INSERT INTO BASETABLE_METADATA VALUES(24,'ENSEMBLGENE_ENSEMBLTRANS',4,0);
INSERT INTO BASETABLE_METADATA VALUES(25,'ENTREZGENE_REFSEQMRNA',5,1);
INSERT INTO BASETABLE_METADATA VALUES(26,'ENSEMBLTRANS_ENSEMBLPROT',6,4);
INSERT INTO BASETABLE_METADATA VALUES(27,'REFSEQMRNA_REFSEQPROTEIN',7,5);

INSERT INTO COLUMN_METADATA VALUES(0,'ESE_ENSEMBLGENEID',0,0);
INSERT INTO COLUMN_METADATA VALUES(1,'ESE_GENEID',0,1);
INSERT INTO COLUMN_METADATA VALUES(2,'ESE_LINKTYPE',0,null);

INSERT INTO COLUMN_METADATA VALUES(3,'EBU_ENSEMBLGENEID',1,0);
INSERT INTO COLUMN_METADATA VALUES(4,'EBU_UNIGENEID',1,2);
INSERT INTO COLUMN_METADATA VALUES(5,'EBU_LINKTYPE',1,null);

INSERT INTO COLUMN_METADATA VALUES(6,'ESN_ENSBLGENEID',2,0);
INSERT INTO COLUMN_METADATA VALUES(7,'ESN_ENSBLTRANSCRIPTID',2,4);
INSERT INTO COLUMN_METADATA VALUES(8,'ESN_LINKTYPE',2,null);

INSERT INTO COLUMN_METADATA VALUES(9,'EEG_GENEID',3,1);
INSERT INTO COLUMN_METADATA VALUES(10,'EEG_ENSEMBLGENEID',3,0);
INSERT INTO COLUMN_METADATA VALUES(11,'EEG_LINKTYPE',3,null);

INSERT INTO COLUMN_METADATA VALUES(12,'EUG_GENEID',4, 1);
INSERT INTO COLUMN_METADATA VALUES(13,'EUG_UGID',4, 2);
INSERT INTO COLUMN_METADATA VALUES(14,'EUG_LINKTYPE',4,null);

INSERT INTO COLUMN_METADATA VALUES(15,'ENR_GENEID',5, 1);
INSERT INTO COLUMN_METADATA VALUES(16,'ENR_REFSEQMRNAID',5, 5);
INSERT INTO COLUMN_METADATA VALUES(17,'ENR_LINKTYPE',5,null);

INSERT INTO COLUMN_METADATA VALUES(18,'UEG_UNIGENEID',6, 2);
INSERT INTO COLUMN_METADATA VALUES(19,'UEG_ENSEMBLGENEID',6, 0);
INSERT INTO COLUMN_METADATA VALUES(20,'UEG_LINKTYPE',6,null);

INSERT INTO COLUMN_METADATA VALUES(21,'UEN_UNIGENEID',7, 2);
INSERT INTO COLUMN_METADATA VALUES(22,'UEN_ENTREZGENEID',7, 1);
INSERT INTO COLUMN_METADATA VALUES(23,'UEN_LINKTYPE',7,null);

INSERT INTO COLUMN_METADATA VALUES(24,'GME_GENBANKMRNAID',8, 3);
INSERT INTO COLUMN_METADATA VALUES(25,'GME_ENSBLTRANSCRIPTID',8, 4);
INSERT INTO COLUMN_METADATA VALUES(26,'GME_LINKTYPE',8,null);

INSERT INTO COLUMN_METADATA VALUES(27,'GMR_GENBANKMRNAID',9, 3);
INSERT INTO COLUMN_METADATA VALUES(28,'GMR_REFSEQMRNAID',9, 5);
INSERT INTO COLUMN_METADATA VALUES(29,'GMR_LINKTYPE',9,null);

INSERT INTO COLUMN_METADATA VALUES(30,'ESR_ENSBLTRANSCRIPTID',10, 4);
INSERT INTO COLUMN_METADATA VALUES(31,'ESR_REFSEQMRNAID',10, 5);
INSERT INTO COLUMN_METADATA VALUES(32,'ESR_LINKTYPE',10,null);

INSERT INTO COLUMN_METADATA VALUES(33,'ESP_ENSBLTRANSCRIPTID',11, 4);
INSERT INTO COLUMN_METADATA VALUES(34,'ESP_ENSBLPROTEINID',11, 6);
INSERT INTO COLUMN_METADATA VALUES(35,'ESP_LINKTYPE',11,null);

INSERT INTO COLUMN_METADATA VALUES(36,'RET_REFSEQMRNAID',12, 5);
INSERT INTO COLUMN_METADATA VALUES(37,'RET_ENSBLTRANSCRIPTID',12, 4);
INSERT INTO COLUMN_METADATA VALUES(38,'RET_LINKTYPE',12,null);

INSERT INTO COLUMN_METADATA VALUES(39,'RER_REFSEQMRNAID',13, 5);
INSERT INTO COLUMN_METADATA VALUES(40,'RER_REFSEQPROTID',13, 7);
INSERT INTO COLUMN_METADATA VALUES(41,'RER_LINKTYPE',13,null);

INSERT INTO COLUMN_METADATA VALUES(42,'EPR_ENSBLPROTEINID',14, 6);
INSERT INTO COLUMN_METADATA VALUES(43,'EPR_REFSEQPROTEINID',14, 7);
INSERT INTO COLUMN_METADATA VALUES(44,'EPR_LINKTYPE',14,null);

INSERT INTO COLUMN_METADATA VALUES(45,'ESU_ENSBLPROTEINID',15, 6);
INSERT INTO COLUMN_METADATA VALUES(46,'ESU_UNIPROTID',15, 9);
INSERT INTO COLUMN_METADATA VALUES(47,'ESU_LINKTYPE',15,null);

INSERT INTO COLUMN_METADATA VALUES(48,'REP_REFSEQPROTEINID',16, 7);
INSERT INTO COLUMN_METADATA VALUES(49,'REP_ENSBLPROTEINID',16, 6);
INSERT INTO COLUMN_METADATA VALUES(50,'REP_LINKTYPE',16,null);

INSERT INTO COLUMN_METADATA VALUES(51,'REU_REFSEQPROTEINID',17, 7);
INSERT INTO COLUMN_METADATA VALUES(52,'REU_UNIPROTKBID',17, 9);
INSERT INTO COLUMN_METADATA VALUES(53,'REU_LINKTYPE',17,null);

INSERT INTO COLUMN_METADATA VALUES(54,'GPE_GENBANKPROTID',18, 8);
INSERT INTO COLUMN_METADATA VALUES(55,'GPE_ENSBLPROTEINID',18, 6);
INSERT INTO COLUMN_METADATA VALUES(56,'GPE_LINKTYPE',18,null);

INSERT INTO COLUMN_METADATA VALUES(57,'GPR_GENBANKPROTID',19, 8);
INSERT INTO COLUMN_METADATA VALUES(58,'GPR_REFSEQPROTEINID',19, 7);
INSERT INTO COLUMN_METADATA VALUES(59,'GPR_LINKTYPE',19,null);

INSERT INTO COLUMN_METADATA VALUES(60,'GPU_GENBANKPROTID',20, 8);
INSERT INTO COLUMN_METADATA VALUES(61,'GPU_UNIPROTID',20, 9);
INSERT INTO COLUMN_METADATA VALUES(62,'GPU_LINKTYPE',20,null);

INSERT INTO COLUMN_METADATA VALUES(63,'UEP_UNIPROTKBID',21, 9);
INSERT INTO COLUMN_METADATA VALUES(64,'UEP_ENSBLPROTEINID',21, 6);
INSERT INTO COLUMN_METADATA VALUES(65,'UEP_LINKTYPE',21,null);

INSERT INTO COLUMN_METADATA VALUES(66,'URE_UNIPROTKBID',22, 9);
INSERT INTO COLUMN_METADATA VALUES(67,'URE_REFSEQPROTEINID',22, 7);
INSERT INTO COLUMN_METADATA VALUES(68,'URE_LINKTYPE',22,null);

INSERT INTO COLUMN_METADATA VALUES(69,'UGE_UNIPROTKBID',23, 9);
INSERT INTO COLUMN_METADATA VALUES(70,'UGE_GENBANKPROTEINID',23, 8);
INSERT INTO COLUMN_METADATA VALUES(71,'UGE_LINKTYPE',23,null);

INSERT INTO COLUMN_METADATA VALUES(72,'ESN_ENSBLGENEID',24, 0);
INSERT INTO COLUMN_METADATA VALUES(73,'ESN_ENSBLTRANSCRIPTID',24, 4);
INSERT INTO COLUMN_METADATA VALUES(74,'ESN_LINKTYPE',24,null);

INSERT INTO COLUMN_METADATA VALUES(75,'ENR_GENEID',25, 1);
INSERT INTO COLUMN_METADATA VALUES(76,'ENR_REFSEQMRNAID',25, 5);
INSERT INTO COLUMN_METADATA VALUES(77,'ENR_LINKTYPE',25,null);

INSERT INTO COLUMN_METADATA VALUES(78,'ESP_ENSBLTRANSCRIPTID',26, 4);
INSERT INTO COLUMN_METADATA VALUES(79,'ESP_ENSBLPROTEINID',26, 6);
INSERT INTO COLUMN_METADATA VALUES(80,'ESP_LINKTYPE',26,null);

INSERT INTO COLUMN_METADATA VALUES(81,'RER_REFSEQMRNAID',27, 5);
INSERT INTO COLUMN_METADATA VALUES(82,'RER_REFSEQPROTID',27, 7);
INSERT INTO COLUMN_METADATA VALUES(83,'RER_LINKTYPE',27,null);



INSERT INTO TABLEJOIN_METADATA VALUES (0,4,1,12);
INSERT INTO TABLEJOIN_METADATA VALUES (0,5,1,15);

INSERT INTO TABLEJOIN_METADATA VALUES (1,7,4,21);

INSERT INTO TABLEJOIN_METADATA VALUES (2,10,7,30);
INSERT INTO TABLEJOIN_METADATA VALUES (2,11,7,33);

INSERT INTO TABLEJOIN_METADATA VALUES (3,1,10,3);
INSERT INTO TABLEJOIN_METADATA VALUES (3,2,10,6);

INSERT INTO TABLEJOIN_METADATA VALUES (4,6,13,18);

INSERT INTO TABLEJOIN_METADATA VALUES (5,12,16,36);
INSERT INTO TABLEJOIN_METADATA VALUES (5,13,16,39);

INSERT INTO TABLEJOIN_METADATA VALUES (6,0,19,0);
INSERT INTO TABLEJOIN_METADATA VALUES (6,2,19,6);

INSERT INTO TABLEJOIN_METADATA VALUES (7,3,22,9);
INSERT INTO TABLEJOIN_METADATA VALUES (7,5,22,15);

INSERT INTO TABLEJOIN_METADATA VALUES (8,10,25,30);
INSERT INTO TABLEJOIN_METADATA VALUES (8,11,25,33);
INSERT INTO TABLEJOIN_METADATA VALUES (8,24,25,73);

INSERT INTO TABLEJOIN_METADATA VALUES (9,12,28,36);
INSERT INTO TABLEJOIN_METADATA VALUES (9,13,28,39);
INSERT INTO TABLEJOIN_METADATA VALUES (9,25,28,76);

INSERT INTO TABLEJOIN_METADATA VALUES (10,13,31,39);
INSERT INTO TABLEJOIN_METADATA VALUES (10,25,31,76);

INSERT INTO TABLEJOIN_METADATA VALUES (11,14,34,42);
INSERT INTO TABLEJOIN_METADATA VALUES (11,15,34,45);

INSERT INTO TABLEJOIN_METADATA VALUES (12,11,37,33);
INSERT INTO TABLEJOIN_METADATA VALUES (12,24,37,73);

INSERT INTO TABLEJOIN_METADATA VALUES (13,16,40,49);
INSERT INTO TABLEJOIN_METADATA VALUES (13,17,40,51);

INSERT INTO TABLEJOIN_METADATA VALUES (14,17,43,51);
INSERT INTO TABLEJOIN_METADATA VALUES (14,27,43,82);

INSERT INTO TABLEJOIN_METADATA VALUES (15,22,46,66);
INSERT INTO TABLEJOIN_METADATA VALUES (15,23,46,69);

INSERT INTO TABLEJOIN_METADATA VALUES (16,15,49,45);
INSERT INTO TABLEJOIN_METADATA VALUES (16,26,49,79);

INSERT INTO TABLEJOIN_METADATA VALUES (17,21,52,63);
INSERT INTO TABLEJOIN_METADATA VALUES (17,23,52,69);

INSERT INTO TABLEJOIN_METADATA VALUES (18,14,55,42);
INSERT INTO TABLEJOIN_METADATA VALUES (18,15,55,45);
INSERT INTO TABLEJOIN_METADATA VALUES (18,26,55,79);

INSERT INTO TABLEJOIN_METADATA VALUES (19,16,58,49);
INSERT INTO TABLEJOIN_METADATA VALUES (19,17,58,51);
INSERT INTO TABLEJOIN_METADATA VALUES (19,27,58,82);

INSERT INTO TABLEJOIN_METADATA VALUES (20,21,61,63);
INSERT INTO TABLEJOIN_METADATA VALUES (20,22,61,66);

INSERT INTO TABLEJOIN_METADATA VALUES (21,14,64,42);
INSERT INTO TABLEJOIN_METADATA VALUES (21,26,64,79);

INSERT INTO TABLEJOIN_METADATA VALUES (22,16,67,48);
INSERT INTO TABLEJOIN_METADATA VALUES (22,27,67,82);

INSERT INTO TABLEJOIN_METADATA VALUES (23,18,70,54);
INSERT INTO TABLEJOIN_METADATA VALUES (23,19,70,57);

INSERT INTO TABLEJOIN_METADATA VALUES (24,0,72,0);
INSERT INTO TABLEJOIN_METADATA VALUES (24,1,72,3);

INSERT INTO TABLEJOIN_METADATA VALUES (25,3,75,9);
INSERT INTO TABLEJOIN_METADATA VALUES (25,4,75,12);

INSERT INTO TABLEJOIN_METADATA VALUES (26,10,78,30);
INSERT INTO TABLEJOIN_METADATA VALUES (26,24,78,73);

INSERT INTO TABLEJOIN_METADATA VALUES (27,12,81,36);
INSERT INTO TABLEJOIN_METADATA VALUES (27,25,81,76);

INSERT INTO ROLE_LOOKUP VALUES(1,'GenomicIdentifierSet','Gene','gene');
INSERT INTO ROLE_LOOKUP VALUES(2,'GenomicIdentifierSet','Protein','protein');
INSERT INTO ROLE_LOOKUP VALUES(3,'GenomicIdentifierSet','MessengerRNA','messengerRNA');
INSERT INTO ROLE_LOOKUP VALUES(4,'GenomicIdentifierSet','OrderOfNodeTraversal','orderOfNodeTraversalCollection');
INSERT INTO ROLE_LOOKUP VALUES(5,'Gene','GenomicIdentifierSet','genomicIdentifierSetCollection');
INSERT INTO ROLE_LOOKUP VALUES(6,'Gene','MessengerRNA','messengerRNACollection');
INSERT INTO ROLE_LOOKUP VALUES(7,'Gene','Protein','proteinCollection');
INSERT INTO ROLE_LOOKUP VALUES(8,'Protein','GenomicIdentifierSet','genomicIdentifierSetCollection');
INSERT INTO ROLE_LOOKUP VALUES(9,'Protein','MessengerRNA','messengerRNACollection');
INSERT INTO ROLE_LOOKUP VALUES(10,'Protein','Gene','geneCollection');
INSERT INTO ROLE_LOOKUP VALUES(11,'MessengerRNA','GenomicIdentifierSet','genomicIdentifierSetCollection');
INSERT INTO ROLE_LOOKUP VALUES(12,'MessengerRNA','Protein','proteinCollection');
INSERT INTO ROLE_LOOKUP VALUES(13,'MessengerRNA','Gene','geneCollection');
INSERT INTO ROLE_LOOKUP VALUES(14,'OrderOfNodeTraversal','GenomicIdentifierSet','genomicIdentifierSetCollection');
INSERT INTO ROLE_LOOKUP VALUES(15,'GenomicIdentifierSet','ConsensusIdentifierData','consensusIdentifierDataCollection');
INSERT INTO ROLE_LOOKUP VALUES(16,'OrderOfNodeTraversal','DataSource','sourceDataSource');
INSERT INTO ROLE_LOOKUP VALUES(17,'OrderOfNodeTraversal','LinkType','linkType');

INSERT INTO GENOMIC_IDENTIFIER VALUES(1,'Ensembl Gene',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(2,'Entrez Gene',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(3,'UniGene',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(4,'Ensembl Transcript',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(5,'GenBank mRNA',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(6,'RefSeq mRNA',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(7,'Ensembl Peptide',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(8,'RefSeq Protein',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(9,'UniProtKB',1,1);
INSERT INTO GENOMIC_IDENTIFIER VALUES(10,'GenBank Protein',1,1);

INSERT INTO SOLUTION VALUES(1);

INSERT INTO CONSENSUS_DATA VALUES(1,1,1,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(2,1,2,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(3,1,3,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(4,1,4,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(5,1,5,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(6,1,6,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(7,1,7,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(8,1,8,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(9,1,9,null,1,1);
INSERT INTO CONSENSUS_DATA VALUES(10,1,10,null,1,1);

INSERT INTO GENE VALUES(0,null,null,null);
INSERT INTO MRNA VALUES(0,null,null,null);
INSERT INTO PROTEIN VALUES(0,null,null,null,null);