CREATE TABLE ENSEMBLGENE_ENTREZGENE
(
	ESE_ENSEMBLGENEID VARCHAR2(30),
	ESE_GENEID NUMBER(12),
	ESE_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (ESE_ENSEMBLGENEID, ESE_GENEID, ESE_LINKTYPE)
	
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLGENE_ENSEMBLTRANS
(
	ESN_ENSBLGENEID VARCHAR2(30),
	ESN_ENSBLTRANSCRIPTID VARCHAR2(30),
	ESN_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (ESN_ENSBLGENEID, ESN_ENSBLTRANSCRIPTID, ESN_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLTRANS_ENSEMBLPROT
(
	ESP_ENSBLTRANSCRIPTID VARCHAR2(30),
	ESP_ENSBLPROTEINID VARCHAR2(30),
	ESP_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (ESP_ENSBLTRANSCRIPTID, ESP_ENSBLPROTEINID, ESP_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLGENE_UNIGENE
(
	EBU_ENSEMBLGENEID VARCHAR2(30),
	EBU_UNIGENEID VARCHAR2(30),
	EBU_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (EBU_ENSEMBLGENEID, EBU_UNIGENEID, EBU_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLTRANS_REFSEQMRNA
(
	ESR_ENSBLTRANSCRIPTID VARCHAR2(30),
	ESR_REFSEQMRNAID VARCHAR2(30),
	ESR_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (ESR_ENSBLTRANSCRIPTID, ESR_REFSEQMRNAID, ESR_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLPROT_REFSEQPROTEIN
(
	EPR_ENSBLPROTEINID VARCHAR2(30),
	EPR_REFSEQPROTEINID VARCHAR2(30),
	EPR_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (EPR_ENSBLPROTEINID, EPR_REFSEQPROTEINID, EPR_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENSEMBLPROT_UNIPROT
(
	ESU_ENSBLPROTEINID VARCHAR2(30),
	ESU_UNIPROTID VARCHAR2(30),
	ESU_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (ESU_ENSBLPROTEINID, ESU_UNIPROTID, ESU_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZGENE_REFSEQMRNA ( 
  ENR_GENEID        NUMBER (12), 
  ENR_REFSEQMRNAID  VARCHAR2 (30), 
  ENR_LINKTYPE      VARCHAR2 (30),
  PRIMARY KEY (ENR_GENEID, ENR_REFSEQMRNAID, ENR_LINKTYPE)
  ) TABLESPACE GENECONNECTDATA;


CREATE TABLE ENTREZGENE ( 
  EGE_GENEID          NUMBER (12)   NOT NULL, 
  EGE_LOCAL_TAXID     NUMBER (12)   NOT NULL, 
  EGE_SYMBOL          VARCHAR2 (30), 
  EGE_GENE_NAME       VARCHAR2 (100), 
  EGE_SUMMARY         VARCHAR2 (4000), 
  EGE_CHROMOSOME_MAP  VARCHAR2 (30), 
  EGE_CHROMOSOME      VARCHAR2 (30), 
  PRIMARY KEY ( EGE_GENEID ) 
  ) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZGENE_ENSEMBLGENE ( 
  EEG_GENEID         NUMBER (12)   NOT NULL, 
  EEG_ENSEMBLGENEID  VARCHAR2 (30)  NOT NULL, 
  EEG_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( EEG_GENEID, EEG_ENSEMBLGENEID, EEG_LINKTYPE )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_FLY ( 
  EFY_GENEID       NUMBER (12)   NOT NULL, 
  EFY_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EFY_FLYID        VARCHAR2 (100)  NOT NULL, 
  PRIMARY KEY ( EFY_GENEID, EFY_FLYID ) 
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_GENENAMES ( 
  EGE_GENEID       NUMBER (12)   NOT NULL, 
  EGE_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EGE_GENE_NAME    VARCHAR2 (100)  NOT NULL, 
  PRIMARY KEY ( EGE_GENEID, EGE_GENE_NAME ) 
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_GOID ( 
  EGO_GENEID       NUMBER (12)   NOT NULL, 
  EGO_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EGO_GOID         VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( EGO_GENEID, EGO_GOID ) 
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_MAP ( 
  EMA_GENEID       NUMBER (12)   NOT NULL, 
  EMA_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EMA_MAPID        VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( EMA_GENEID, EMA_MAPID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_OMIM ( 
  EOM_GENEID       NUMBER (12)   NOT NULL, 
  EOM_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EOM_OMIM         NUMBER (8)    NOT NULL, 
  PRIMARY KEY ( EOM_GENEID, EOM_OMIM )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_PHENOTYPE ( 
  EPH_GENEID       NUMBER (12)   NOT NULL, 
  EPH_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EPH_PHENOTYPE    VARCHAR2 (255)  NOT NULL, 
  PRIMARY KEY ( EPH_GENEID, EPH_PHENOTYPE )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_PMIDS ( 
  EPI_GENEID       NUMBER (12)   NOT NULL, 
  EPI_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EPI_PUBMEDID     NUMBER (10)   NOT NULL, 
  PRIMARY KEY ( EPI_GENEID, EPI_PUBMEDID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_STS ( 
  EST_GENEID       NUMBER (12)   NOT NULL, 
  EST_LOCAL_TAXID  NUMBER (12), 
  EST_STSID        NUMBER (10)   NOT NULL, 
  PRIMARY KEY ( EST_GENEID, EST_STSID ) 
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ENTREZ_UNIGENE ( 
  EUG_GENEID       NUMBER (12)   NOT NULL, 
  EUG_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  EUG_UGID         VARCHAR2 (23)  NOT NULL, 
  EUG_LINKTYPE     VARCHAR2 (30), 
  PRIMARY KEY ( EUG_GENEID, EUG_UGID, EUG_LINKTYPE  )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE GENBANKMRNA_ENSEMBLTRANS (
	GME_GENBANKMRNAID VARCHAR(30),
	GME_ENSBLTRANSCRIPTID VARCHAR2(30),
	GME_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (GME_GENBANKMRNAID, GME_ENSBLTRANSCRIPTID, GME_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE GENBANKMRNA_REFSEQMRNA (
	GMR_GENBANKMRNAID VARCHAR(30),
	GMR_REFSEQMRNAID VARCHAR2(30),
	GMR_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (GMR_GENBANKMRNAID, GMR_REFSEQMRNAID, GMR_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE GENBANKPROT_ENSEMBLPROT (
	GPE_GENBANKPROTID VARCHAR(30),
	GPE_ENSBLPROTEINID VARCHAR2(30),
	GPE_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (GPE_GENBANKPROTID, GPE_ENSBLPROTEINID, GPE_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE GENBANKPROT_REFSEQPROTEIN (
	GPR_GENBANKPROTID VARCHAR(30),
	GPR_REFSEQPROTEINID VARCHAR2(30),
	GPR_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (GPR_GENBANKPROTID, GPR_REFSEQPROTEINID, GPR_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE GENBANKPROT_UNIPROT (
	GPU_GENBANKPROTID VARCHAR(30),
	GPU_UNIPROTID VARCHAR2(30),
	GPU_LINKTYPE VARCHAR2(30),
	PRIMARY KEY (GPU_GENBANKPROTID, GPU_UNIPROTID, GPU_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ORGANISM_TAXONOMYMAP ( 
  OTM_LOCAL_TAXID  NUMBER (12)   NOT NULL, 
  OTM_TAXID        NUMBER (12), 
  OTM_ORGNAME      VARCHAR2 (100), 
  PRIMARY KEY ( OTM_LOCAL_TAXID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE ORGANISM_TAXONOMYMAP_TMP ( 
  OTT_TAXID    NUMBER (12)   NOT NULL, 
  OTT_ORGNAME  VARCHAR2 (100), 
  PRIMARY KEY ( OTT_TAXID )
)TABLESPACE GENECONNECTDATA; 

CREATE TABLE ORGANISM_TAXONOMY_HISTORY ( 
  OTH_OLDTAXID  NUMBER (12)   NOT NULL, 
  OTH_NEWTAXID  NUMBER (12)   NOT NULL, 
  PRIMARY KEY ( OTH_OLDTAXID, OTH_NEWTAXID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE REFSEQMRNA_REFSEQPROTEIN ( 
  RER_REFSEQMRNAID  VARCHAR2 (30), 
  RER_REFSEQPROTID  VARCHAR2 (30), 
  RER_LINKTYPE      VARCHAR2 (30),
  PRIMARY KEY (RER_REFSEQMRNAID, RER_REFSEQPROTID, RER_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE REFSEQMRNA_ENSEMBLTRANS ( 
  RET_REFSEQMRNAID         VARCHAR2 (30) NOT NULL, 
  RET_ENSBLTRANSCRIPTID  VARCHAR2 (30)  NOT NULL, 
  RET_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( RET_REFSEQMRNAID, RET_ENSBLTRANSCRIPTID, RET_LINKTYPE )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE REFSEQPROTEIN_UNIPROT ( 
  REU_REFSEQPROTEINID         VARCHAR2 (30) NOT NULL, 
  REU_UNIPROTKBID  VARCHAR2 (30)  NOT NULL, 
  REU_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( REU_REFSEQPROTEINID, REU_UNIPROTKBID, REU_LINKTYPE )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE REVISION_HISTORY ( 
  RVH_LOCAL_TAXID      NUMBER (12)   NOT NULL, 
  RVH_ENTREZ_VERSION   VARCHAR2 (30), 
  RVH_UNIGENE_VERSION  VARCHAR2 (30), 
  RVH_UNI_STS_VERSION  VARCHAR2 (30), 
  RVH_GO_VERSION       VARCHAR2 (30), 
  RVH_HML_VERSION      VARCHAR2 (30), 
  RVH_TAX_VERSION      VARCHAR2 (30), 
  RVH_DBSNP_VERSION    VARCHAR2 (30), 
  PRIMARY KEY ( RVH_LOCAL_TAXID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE SERVER_FILE_STATUS ( 
  SFS_ID           NUMBER (10), 
  SFS_MODIFY_DATE  DATE, 
  SFS_FILENAME     VARCHAR2 (50), 
  SFS_FILETYPE     VARCHAR2 (8), 
  SFS_DATABASE     VARCHAR2 (10), 
  SFS_PATH         VARCHAR2 (30), 
  REVISION_NUMBER  VARCHAR2 (30)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE SERVER_STATUS ( 
  SST_ID                    NUMBER (10)   NOT NULL, 
  SST_EXECUTION_DATE        DATE, 
  SST_EXECUTION_MODE        CHAR (1), 
  SST_MACHINENAME           VARCHAR2 (30), 
  SST_PARSING_TIME          NUMBER (10), 
  SST_TOTAL_TIME            NUMBER (10), 
  SST_ERROR_COUNT           NUMBER (3), 
  SST_POSTWORK_ERROR_COUNT  NUMBER (3), 
  PRIMARY KEY ( SST_ID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE SYSTEM_TERMDATA ( 
  STD_TERMID  VARCHAR2 (30)  NOT NULL, 
  STD_TERM    VARCHAR2 (255)  NOT NULL, 
  PRIMARY KEY ( STD_TERMID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE SYSTEM_TERMTREE ( 
  STT_CHILD_TERMID   VARCHAR2 (30)  NOT NULL, 
  STT_PARENT_TERMID  VARCHAR2 (30)  NOT NULL, 
  STT_ISPARENT       CHAR (1)      NOT NULL, 
  PRIMARY KEY ( STT_CHILD_TERMID, STT_PARENT_TERMID )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE UNIGENE ( 
  GENEID  VARCHAR2 (30), 
  TITLE   VARCHAR2 (500), 
  GENE    VARCHAR2 (30), 
  ORG     VARCHAR2 (30), 
  TAXID   VARCHAR2 (20)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE UNIGENE_ENTREZ ( 
  UEN_UNIGENEID     VARCHAR2 (30)  NOT NULL, 
  UEN_ENTREZGENEID  NUMBER (12)   NOT NULL, 
  UEN_LINKTYPE      VARCHAR2 (30), 
  PRIMARY KEY ( UEN_UNIGENEID, UEN_ENTREZGENEID, UEN_LINKTYPE )
) TABLESPACE GENECONNECTDATA;

CREATE TABLE UNIPROT_GENBANKPROTEIN ( 
  UGE_UNIPROTKBID       VARCHAR2 (30), 
  UGE_GENBANKPROTEINID  VARCHAR2 (30), 
  UGE_LINKTYPE          VARCHAR2 (30),
  PRIMARY KEY (UGE_UNIPROTKBID, UGE_GENBANKPROTEINID, UGE_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE UNIPROT_REFSEQPROTEIN ( 
  URE_UNIPROTKBID      VARCHAR2 (30), 
  URE_REFSEQPROTEINID  VARCHAR2 (30), 
  URE_LINKTYPE         VARCHAR2 (30),
  PRIMARY KEY (URE_UNIPROTKBID, URE_REFSEQPROTEINID, URE_LINKTYPE)
) TABLESPACE GENECONNECTDATA;

CREATE TABLE UNIGENE_ENSEMBLGENE ( 
  UEG_UNIGENEID      VARCHAR2 (30)  NOT NULL, 
  UEG_ENSEMBLGENEID  VARCHAR2 (30)  NOT NULL, 
  UEG_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( UEG_UNIGENEID, UEG_ENSEMBLGENEID, UEG_LINKTYPE )
) TABLESPACE GENECONNECTDATA;
  
CREATE TABLE UNIPROT_ENSEMBLPROT ( 
  UEP_UNIPROTKBID   VARCHAR2 (30) NOT NULL, 
  UEP_ENSBLPROTEINID  VARCHAR2 (30)  NOT NULL, 
  UEP_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( UEP_UNIPROTKBID, UEP_ENSBLPROTEINID, UEP_LINKTYPE  )
) TABLESPACE GENECONNECTDATA;
  
CREATE TABLE REFSEQPROTEIN_ENSEMBLPROT (
  REP_REFSEQPROTEINID    VARCHAR2 (30) NOT NULL, 
  REP_ENSBLPROTEINID   VARCHAR2 (30)  NOT NULL, 
  REP_LINKTYPE       VARCHAR2 (30)  NOT NULL, 
  PRIMARY KEY ( REP_REFSEQPROTEINID, REP_ENSBLPROTEINID, REP_LINKTYPE )
) TABLESPACE GENECONNECTDATA;
   
   