DROP TABLE GENE_U CASCADE CONSTRAINTS
;
DROP TABLE GENE_MRNA_U CASCADE CONSTRAINTS
;
DROP TABLE GENOMIC_IDENTIFIER_SET_U CASCADE CONSTRAINTS
;
DROP TABLE MRNA_U CASCADE CONSTRAINTS
;
DROP TABLE MRNA_PROTEIN_U CASCADE CONSTRAINTS
;
DROP TABLE PROTEIN_U CASCADE CONSTRAINTS
;
DROP TABLE PROTEIN_GENE_U CASCADE CONSTRAINTS
;
DROP TABLE SET_ONT_U CASCADE CONSTRAINTS
;
DROP TABLE GENOMIC_IDENTIFIER_SET_ONT_1_U CASCADE CONSTRAINTS
;
DROP TABLE GENOMIC_IDENTIFIER_SET_ONT_2_U CASCADE CONSTRAINTS
;
DROP TABLE GENOMIC_IDENTIFIER_SET_ONT_3_U CASCADE CONSTRAINTS
;
DROP TABLE GENOMIC_IDENTIFIER_SET_ONT_4_U CASCADE CONSTRAINTS
;


CREATE TABLE GENE_U ( 
	GENE_ID NUMBER(20) NOT NULL,
	ENSEMBL_GENE_ID VARCHAR2(50),
	ENTREZ_GENE_ID NUMBER(8),
	UNIGENE_CLUSTER_ID VARCHAR2(50)
)
;

CREATE TABLE GENE_MRNA_U ( 
	GENE_ID NUMBER(20) NOT NULL,
	MRNA_ID NUMBER(20) NOT NULL
)
;

CREATE TABLE GENOMIC_IDENTIFIER_SET_U ( 
	SET_ID NUMBER(20) NOT NULL,
	GENE_ID NUMBER(20),
	MRNA_ID NUMBER(20),
	PROTEIN_ID NUMBER(20),
	SOLUTION_ID NUMBER(8)
)
;

CREATE TABLE MRNA_U ( 
	MRNA_ID NUMBER(20) NOT NULL,
	ENSEMBL_TRANSCRIPT_ID VARCHAR2(50),
	GENBANK_MRNA_ACCESSION VARCHAR2(50),
	REFSEQ_MRNA_ID VARCHAR2(50)
)
;

CREATE TABLE MRNA_PROTEIN_U ( 
	MRNA_ID NUMBER(20) NOT NULL,
	PROTEIN_ID NUMBER(20) NOT NULL
)
;

CREATE TABLE PROTEIN_U ( 
	PROTEIN_ID NUMBER(20) NOT NULL,
	ENSEMBL_PEPTIDE_ID VARCHAR2(50),
	REFSEQ_PROTEIN_ID VARCHAR2(50),
	UNIPROTKB_ACCESSION VARCHAR2(50),
	GENEBANK_PROTEIN_ACCESSION VARCHAR2(50)
)
;

CREATE TABLE PROTEIN_GENE_U ( 
	PROTEIN_ID NUMBER(20) NOT NULL,
	GENE_ID NUMBER(20) NOT NULL
)
;

CREATE TABLE SET_ONT_U ( 
	SET_ID NUMBER(20) NOT NULL,
	PATH_ID NUMBER(8)
)
;

CREATE TABLE GENOMIC_IDENTIFIER_SET_ONT_1_U ( 
	ENSEMBL_GENE_ID VARCHAR2(50),
	ENTREZ_GENE_ID NUMBER(8),
	UNIGENE_CLUSTER_ID VARCHAR2(50),
	ENSEMBL_TRANSCRIPT_ID VARCHAR2(50),
	GENBANK_MRNA_ACCESSION VARCHAR2(50),
	REFSEQ_MRNA_ID VARCHAR2(50),
	ENSEMBL_PEPTIDE_ID VARCHAR2(50),
	REFSEQ_PROTEIN_ID VARCHAR2(50),
	UNIPROTKB_ACCESSION VARCHAR2(50),
	GENEBANK_PROTEIN_ACCESSION VARCHAR2(50),
	PATH_ID NUMBER(8)
);


CREATE TABLE GENOMIC_IDENTIFIER_SET_ONT_2_U ( 
	GENE_ID NUMBER(20),
	ENSEMBL_TRANSCRIPT_ID VARCHAR2(50),
	GENBANK_MRNA_ACCESSION VARCHAR2(50),
	REFSEQ_MRNA_ID VARCHAR2(50),
	ENSEMBL_PEPTIDE_ID VARCHAR2(50),
	REFSEQ_PROTEIN_ID VARCHAR2(50),
	UNIPROTKB_ACCESSION VARCHAR2(50),
	GENEBANK_PROTEIN_ACCESSION VARCHAR2(50),
	PATH_ID NUMBER(8)
);


CREATE TABLE GENOMIC_IDENTIFIER_SET_ONT_3_U ( 
	GENE_ID NUMBER(20),
	MRNA_ID NUMBER(20),
	ENSEMBL_PEPTIDE_ID VARCHAR2(50),
	REFSEQ_PROTEIN_ID VARCHAR2(50),
	UNIPROTKB_ACCESSION VARCHAR2(50),
	GENEBANK_PROTEIN_ACCESSION VARCHAR2(50),
	PATH_ID NUMBER(8)
);


CREATE TABLE GENOMIC_IDENTIFIER_SET_ONT_4_U ( 
	GENE_ID NUMBER(20),
	MRNA_ID NUMBER(20),
	PROTEIN_ID NUMBER(20),
	PATH_ID NUMBER(8)
);



CREATE INDEX GENE_INDEX ON GENE_U(GENE_ID)
;

CREATE INDEX GENE_MRNA_INDEX_GENE_ID ON GENE_MRNA_U(GENE_ID)
;
CREATE INDEX GENE_MRNA_INDEX_MRNA_ID ON GENE_MRNA_U(MRNA_ID)
;


CREATE INDEX MRNA_INDEX ON  MRNA_U(MRNA_ID)
;

CREATE INDEX MRNA_PROTEIN_INDEX_MRNA_ID ON  MRNA_PROTEIN_U(MRNA_ID)
;
CREATE INDEX MRNA_PROTEIN_INDEX_PROTEIN_ID ON  MRNA_PROTEIN_U(PROTEIN_ID)
;



CREATE INDEX PROTEIN_INDEX ON  PROTEIN_U(PROTEIN_ID)
;

CREATE INDEX PROTEIN_GENE_INDEX_PROTEIN_ID ON  PROTEIN_GENE_U (PROTEIN_ID)
;
CREATE INDEX PROTEIN_GENE_INDEX_GENE_ID ON  PROTEIN_GENE_U (GENE_ID)
;


CREATE INDEX SET_SETID_INDEX ON GENOMIC_IDENTIFIER_SET_U(SET_ID)
;
CREATE INDEX SET_GENE_ID_INDEX ON GENOMIC_IDENTIFIER_SET_U(GENE_ID)
;
CREATE INDEX SET_MRNA_ID_INDEX ON GENOMIC_IDENTIFIER_SET_U(MRNA_ID)
;
CREATE INDEX SET_PROTEIN_ID_INDEX ON GENOMIC_IDENTIFIER_SET_U(PROTEIN_ID)
;

CREATE INDEX SET_ONT_SETID_INDEX ON SET_ONT_U(SET_ID)
;
CREATE INDEX SET_ONT_PATHID_INDEX ON SET_ONT_U(PATH_ID)
;


ALTER TABLE SET_ONT_U ADD CONSTRAINT PK_SET_ONT_U 
	PRIMARY KEY (PATH_ID, SET_ID) 
;
ALTER TABLE GENE_MRNA_U ADD CONSTRAINT PK_GENE_MRNA_ID_U
	PRIMARY KEY (GENE_ID, MRNA_ID)
;
ALTER TABLE MRNA_PROTEIN_U ADD CONSTRAINT PK_MRNA_PROTEIN_ID_U
	PRIMARY KEY (MRNA_ID, PROTEIN_ID)
;
ALTER TABLE PROTEIN_GENE_U ADD CONSTRAINT PK_PROTEIN_GENE_ID_U
	PRIMARY KEY (PROTEIN_ID, GENE_ID)
;