
package edu.wustl.geneconnect.domain;

/**
 * <!-- LICENSE_TEXT_START -->
 * <!-- LICENSE_TEXT_END -->
 */

/**
 * Contains the actual instance (e.g. Entrez Gene ID 1958) of each genomic identifier that satisfies 
 * the GeneConnect query and its frequency across all result sets 
 * 
 */

public class ConsensusIdentifierData implements java.io.Serializable
{

	private static final long serialVersionUID = 1234567890L;
/**
 * Unique identifier of the Consensus Identifier Data object.
 */
	private java.lang.Long id;
/**
 * Returns the unique identifier of the Consensus Identifier Data object.
 * @return unique identifier 
 */
	public java.lang.Long getId()
	{
		return id;
	}
/**
 * Sets the unique identifier of the Consensus Identifier Data object.
 * @param id
 */
	public void setId(java.lang.Long id)
	{
		this.id = id;
	}
/**
 * The ratio of number of rows of result data set in which the genomic identifier 
 * occurs to the total number of rows in the result data set.
 */
	private java.lang.Float frequency;
/**
 * Returns the ratio of number of rows of result data set in which the genomic identifier 
 * occurs to the total number of rows in the result data set.
 * @return frequency
 */
	public java.lang.Float getFrequency()
	{
		return frequency;
	}
/**
 * Sets the ratio of number of rows of result data set in which the genomic identifier 
 * occurs to the total number of rows in the result data set.
 * @param frequency
 */
	public void setFrequency(java.lang.Float frequency)
	{
		this.frequency = frequency;
	}
/**
 * Associated GenomicIdentifierSet object with this ConsensusIdentifierData.
 * @see edu.wustl.geneconnect.domain.GenomicIdentifierSet
 */
	private edu.wustl.geneconnect.domain.GenomicIdentifierSet genomicIdentifierSet;

	/**
	 * Modified the implementation generated by caCore SDK as the GenomicIdentifierSet object 
	 * is set in a  business logic while calculating frequency.
	 * Returns the associated GenomicIdentifierSet object with this ConsensusIdentifierData.
	 * @return genomicIdentifierSet
	 */
	public edu.wustl.geneconnect.domain.GenomicIdentifierSet getGenomicIdentifierSet()
	{
		/**
		 * Removed a statement calling ApplicationService to get GEnomicIdentifierSet.
		 * The GenomiIdentifierSet object is set in a  business logic (OrmDaoImpl.java)  
		 * while calculating frequency. 
		 */
		return genomicIdentifierSet;
	}
	/**
	 * Sets the GenomicIdentifierSet object with this ConsensusIdentifierData.
	 * @param genomicIdentifierSet
	 */
	public void setGenomicIdentifierSet(
			edu.wustl.geneconnect.domain.GenomicIdentifierSet genomicIdentifierSet)
	{
		this.genomicIdentifierSet = genomicIdentifierSet;
	}
	/**
	 * Associated GenomicIdentifier object with this ConsensusIdentifierData.
	 * Genomic Identifier denotes one of the genomic data sources.
	 * @see edu.wustl.geneconnect.domain.GenomicIdentifier
	 */
	private edu.wustl.geneconnect.domain.GenomicIdentifier genomicIdentifier;

	/**
	 * Modified the implementation generated by caCore SDK as the GenomicIdentifier object 
	 * is set in a  business logic while calculating frequency.
	 * Returns the associated GenomicIdentifier object with this ConsensusIdentifierData.
	 *  @return genomicIdentifier
	 */
	public edu.wustl.geneconnect.domain.GenomicIdentifier getGenomicIdentifier()
	{
		/**
		 * Removed a statement calling ApplicationService to get GenomicIdentifier.
		 * The GenomiIdentifier object is set in a  business logic (OrmDaoImpl.java)  
		 * while calculating frequency. 
		 */
		return genomicIdentifier;
	}
/**
 *  Sets the associated GenomicIdentifier object with this ConsensusIdentifierData.
 * @param genomicIdentifier
 */
	public void setGenomicIdentifier(
			edu.wustl.geneconnect.domain.GenomicIdentifier genomicIdentifier)
	{
		this.genomicIdentifier = genomicIdentifier;
	}
/**
 * Associated GenomicIdentifierSolution object with this ConsensusIdentifierData.
 * Encapsulates the result set of a GeneConnect query.
 * @see edu.wustl.geneconnect.GenomicIdentifierSolution
 */
	private edu.wustl.geneconnect.GenomicIdentifierSolution genomicIdentifierSolution;
/**
 * Returns the associated GenomicIdentifierSolution object with this ConsensusIdentifierData.
 * @return genomicIdentifierSolution
 */
	public edu.wustl.geneconnect.GenomicIdentifierSolution getGenomicIdentifierSolution()
	{

		return genomicIdentifierSolution;

	}
/**
 * Sets the GenomicIdentifierSolution object with this ConsensusIdentifierData.
 * @param genomicIdentifierSolution
 */
	public void setGenomicIdentifierSolution(
			edu.wustl.geneconnect.GenomicIdentifierSolution genomicIdentifierSolution)
	{
		this.genomicIdentifierSolution = genomicIdentifierSolution;
	}

	public boolean equals(Object obj)
	{
		boolean eq = false;
		if (obj instanceof ConsensusIdentifierData)
		{
			ConsensusIdentifierData c = (ConsensusIdentifierData) obj;
			Long thisId = getId();

			if (thisId != null && thisId.equals(c.getId()))
			{
				eq = true;
			}

		}
		return eq;
	}

	public int hashCode()
	{
		int h = 0;

		if (getId() != null)
		{
			h += getId().hashCode();
		}

		return h;
	}

}