/*L
  Copyright Washington University at St. Louis

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/geneconnect/LICENSE.txt for details.
L*/

DROP TABLE ENSEMBLGENE_ENTREZGENE
;
DROP TABLE ENSEMBLGENE_ENSEMBLTRANS
;
DROP TABLE ENSEMBLTRANS_ENSEMBLPROT
;
DROP TABLE ENSEMBLGENE_UNIGENE
;
DROP TABLE ENSEMBLTRANS_REFSEQMRNA
;
DROP TABLE ENSEMBLPROT_REFSEQPROTEIN
;
DROP TABLE ENSEMBLPROT_UNIPROT
;
DROP TABLE ENTREZGENE_REFSEQMRNA
;
DROP TABLE ENTREZGENE_ENSEMBLGENE
;
DROP TABLE ENTREZ_UNIGENE
;
DROP TABLE GENBANKMRNA_ENSEMBLTRANS
;
DROP TABLE GENBANKMRNA_REFSEQMRNA
;
DROP TABLE GENBANKPROT_ENSEMBLPROT
;
DROP TABLE GENBANKPROT_REFSEQPROTEIN
;
DROP TABLE GENBANKPROT_UNIPROT
;
DROP TABLE REFSEQMRNA_REFSEQPROTEIN
;
DROP TABLE REFSEQMRNA_ENSEMBLTRANS
;
DROP TABLE REFSEQPROTEIN_UNIPROT
;
DROP TABLE UNIGENE_ENTREZ
;
DROP TABLE UNIPROT_GENBANKPROTEIN
;
DROP TABLE UNIPROT_REFSEQPROTEIN
;
DROP TABLE UNIGENE_ENSEMBLGENE
;
DROP TABLE UNIPROT_ENSEMBLPROT
;
DROP TABLE REFSEQPROTEIN_ENSEMBLPROT
;


ALTER TABLE ENSEMBLGENE_ENTREZGENE_U RENAME TO ENSEMBLGENE_ENTREZGENE
;
ALTER TABLE ENSEMBLGENE_ENSEMBLTRANS_U RENAME TO ENSEMBLGENE_ENSEMBLTRANS
;
ALTER TABLE ENSEMBLTRANS_ENSEMBLPROT_U RENAME TO ENSEMBLTRANS_ENSEMBLPROT
;
ALTER TABLE ENSEMBLGENE_UNIGENE_U RENAME TO ENSEMBLGENE_UNIGENE
;
ALTER TABLE ENSEMBLTRANS_REFSEQMRNA_U RENAME TO ENSEMBLTRANS_REFSEQMRNA
;
ALTER TABLE ENSEMBLPROT_REFSEQPROTEIN_U	RENAME TO ENSEMBLPROT_REFSEQPROTEIN
;
ALTER TABLE ENSEMBLPROT_UNIPROT_U RENAME TO ENSEMBLPROT_UNIPROT
;
ALTER TABLE ENTREZGENE_REFSEQMRNA_U RENAME TO ENTREZGENE_REFSEQMRNA
;
ALTER TABLE ENTREZGENE_ENSEMBLGENE_U RENAME TO ENTREZGENE_ENSEMBLGENE
;
ALTER TABLE ENTREZ_UNIGENE_U RENAME TO ENTREZ_UNIGENE
;
ALTER TABLE GENBANKMRNA_ENSEMBLTRANS_U RENAME TO GENBANKMRNA_ENSEMBLTRANS
;
ALTER TABLE GENBANKMRNA_REFSEQMRNA_U RENAME TO GENBANKMRNA_REFSEQMRNA
;
ALTER TABLE GENBANKPROT_ENSEMBLPROT_U RENAME TO GENBANKPROT_ENSEMBLPROT
;
ALTER TABLE GENBANKPROT_REFSEQPROTEIN_U RENAME TO GENBANKPROT_REFSEQPROTEIN
;
ALTER TABLE GENBANKPROT_UNIPROT_U RENAME TO GENBANKPROT_UNIPROT
;
ALTER TABLE REFSEQMRNA_REFSEQPROTEIN_U RENAME TO REFSEQMRNA_REFSEQPROTEIN
;
ALTER TABLE REFSEQMRNA_ENSEMBLTRANS_U RENAME TO REFSEQMRNA_ENSEMBLTRANS
;
ALTER TABLE REFSEQPROTEIN_UNIPROT_U RENAME TO REFSEQPROTEIN_UNIPROT
;
ALTER TABLE UNIGENE_ENTREZ_U RENAME TO UNIGENE_ENTREZ
;
ALTER TABLE UNIPROT_GENBANKPROTEIN_U RENAME TO UNIPROT_GENBANKPROTEIN
;
ALTER TABLE UNIPROT_REFSEQPROTEIN_U RENAME TO UNIPROT_REFSEQPROTEIN
;
ALTER TABLE UNIGENE_ENSEMBLGENE_U RENAME TO UNIGENE_ENSEMBLGENE
;
ALTER TABLE UNIPROT_ENSEMBLPROT_U RENAME TO UNIPROT_ENSEMBLPROT
;
ALTER TABLE REFSEQPROTEIN_ENSEMBLPROT_U RENAME TO REFSEQPROTEIN_ENSEMBLPROT
;
